// Generated by scripts/generate-official-lock.mjs; do not edit.
// Module rationale: generated official-skill lock table is kept
// contiguous so digest/version updates remain mechanical and reviewable.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct OfficialSkillLockEntry {
    pub(crate) skill_id: &'static str,
    pub(crate) version: &'static str,
    pub(crate) digest: &'static str,
}

pub(crate) const OFFICIAL_SKILLS: &[OfficialSkillLockEntry] = &[
    OfficialSkillLockEntry {
        skill_id: "runx/adopt-skill",
        version: "sha-022d72addefb",
        digest: "3ebb56f93d53f2187b87f7a558ff2705427e8f06caf2134edde4f32ff9cad136",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/agency",
        version: "sha-68f7eec70760",
        digest: "66db0e30af53394728876dc5c6df833f231c7f7b8ae13d3893acb35177675af8",
    },
    OfficialSkillLockEntry {
        skill_id: "zhtwangk/answer-from-docs",
        version: "sha-934544f2bca4",
        digest: "55b3d2e3558bca9ac6a68f21ecc01865a21781a94a1b7c87719bb11985774faa",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/audit-receipt",
        version: "sha-f040bf60cc7a",
        digest: "0899fa110626cfafe27cf6ffebf7466789652d8ea0089cde66d9e716d9258b48",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/brand-voice",
        version: "sha-0e3d0a2eeb1c",
        digest: "4a1c116664b67eeac12e8490735cba5f7cd0c80cb071b294bb6a3f58b80546e9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/business-ops",
        version: "sha-488ed70df3fd",
        digest: "e5ed9fcb81e70a073232c65035c60f32e7c53e8660e1b1277da7097d8f1606e0",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/charge",
        version: "sha-05ac27e14120",
        digest: "593e65e82d35ba7f3926d1623c73245b80e1597216aa423a966083f8363264eb",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/chief-of-staff",
        version: "sha-4b59a504f22d",
        digest: "9fadb6380a76390dbcbeba0eed904ca568787189653f352404ca7dfb48d09ce9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/content-pipeline",
        version: "sha-f7e37149abdb",
        digest: "2f37f66a7062ee26e868b4be51ff5caf18657f4fba9034ca9908491e37c63675",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/contract-drafter",
        version: "sha-99f958c38dee",
        digest: "63d51951256ec45a7962b4a7bc03dc2e39404925510938ce7839234aa118f529",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/crm-cleanup",
        version: "sha-e2c56d35d30b",
        digest: "709841e7bc7848204fba9ce2be4603d0746e716651f9a90a2be5976ebcc8e9be",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/cve-audit",
        version: "sha-584ebce1db68",
        digest: "f854fc78beabc4d704dc7a3b209ac7e47bf32b1a94d7efd56ff0860d1a14dd51",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/data-store",
        version: "sha-4fb1c8b6641c",
        digest: "d3d15497ed1b541d779b7286dc5bf26ddfdbd510b27abd9b65465415e98b0365",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/data-subject-request",
        version: "sha-b38526fc6f7b",
        digest: "65a6d4775a6e222554c53f1048efe7809093e9dd1f63a33146b5ce7c2acb5060",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/deep-research",
        version: "sha-dbc1fa2abad7",
        digest: "90770d1d99fe3f6ef5fe93f30c1ea0bcdd5834815faa3af9e5a2d7eaec4d3eb6",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/diagnose-skill-run",
        version: "sha-3649a1a5f94d",
        digest: "561b70f0514ebdcc4ee86ae1d1bf7f0b3d0abbc8a723607f40bb54e9977bc08c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/dispute-respond",
        version: "sha-5caa971f8d10",
        digest: "7d4f7a6fe2965a2e91b08823101533fb205303f9fbc7e711a46bab1766b6243a",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ecosystem-brief",
        version: "sha-c8e6c478ca7d",
        digest: "6f4fa6b0f4b4f90e66d4dc11f3e450a81b5e13274c9a3bb5318a28f9807f814e",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/extract",
        version: "sha-a01211bbb608",
        digest: "2f35b36a441ae48d706a88644f1dd47b257ceca08ea0917d065a79957d904486",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ghostwrite",
        version: "sha-07440343bc47",
        digest: "037e4ebc23cdb31bdaa14b498ea705ceb23764efba0904eb743915f1fbf48ef9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/github-pr-comment",
        version: "sha-ce1a4ba97c98",
        digest: "7a733113eaeeb1f9039de9dc649a194880e461eedc63951006879a9ec58600f4",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/github-sync",
        version: "sha-c8d2b97ad77d",
        digest: "2ebf53406127cf05616a9fe98860f08f58dde17e2449d96f286e4efe68062656",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/google-analytics",
        version: "sha-84e595499197",
        digest: "d6c23b6ec788fc4f06711c445ed8faa3121b2705568dcda805d4635cc29a8bd2",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/google-search-console",
        version: "sha-71ae1297a98f",
        digest: "58034fe89c3893b58c97cf00a1282283423545ba3c9472312846b1f8db2088a6",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/governed-outbound",
        version: "sha-fada63123b7b",
        digest: "f9db53424eff6313c07c449a1bcc7e24861de3fdf8974750cacc0901ff708458",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/helpdesk",
        version: "sha-fb3557edef3b",
        digest: "466709c95a9863851587e5e0c29662428b89bdc81a58f82da9fac79db5a78fd2",
    },
    OfficialSkillLockEntry {
        skill_id: "mossony/incident-commander",
        version: "sha-cbd451da5193",
        digest: "f0cf1babd164ed21d742712fe4471fe998ce2ee39121b792a3158d9926b79510",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/issue-intake",
        version: "sha-923f95685163",
        digest: "cee1320a8a8e38800170a5883a279da81e67ccc19558df74a47b797e4a416d2f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/issue-to-pr",
        version: "sha-74a2933f5c79",
        digest: "5519e4e62a2c827f6ee47a8760d10c7e4d97a670be6a2da26234ff2840fe5b2e",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/issue-triage",
        version: "sha-a4d9e81c49b6",
        digest: "0f6946bd2f1d259d7ce2db025025d4a1b34327afaabb3784d211ae21d917f622",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/knowledge-router",
        version: "sha-5dc9d2730b3f",
        digest: "e148d7ebf0163c2c1f38b1b55c821e29fb7418c04d361a4e9485e4aca6ef7966",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/lead-enrichment",
        version: "sha-564c3f07f388",
        digest: "5e0d371bc8a6bb178d0b355abad9a0bf3ae6046ed199f38fe850ce64c48f27e7",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/lead-router",
        version: "sha-52bdeb5d7887",
        digest: "f875a05d9e79a2573d3152430093971462f25086ae0518ecee29f0d69e8e3491",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/least-privilege",
        version: "sha-303d7c9f1f4e",
        digest: "537ba446b892ac397a217dc2c8d4159192cf0ea801e9c595cd72b8d550be61b8",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ledger",
        version: "sha-e598d39910c9",
        digest: "9e3370c09616f2ae0490bfacbf9e944a4631f3e9569c71f2d00133ee1c939afe",
    },
    OfficialSkillLockEntry {
        skill_id: "zhtwangk/meeting-followup",
        version: "sha-d007ef86ba8c",
        digest: "85a1476c09e4f4c68b21f97c61a260eaff2e29dd3dc19b92deb3f9dfc6871c08",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/messageboard",
        version: "sha-6107e90ef312",
        digest: "142f630916dc7da8ab6f8558dcab8becf96037cbad1365e2d324a11d35216c65",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mock-charge",
        version: "sha-e90553887a62",
        digest: "40f9cb0afba40701cc11d3f66259207f166d7b58a5a10e058c00b18935d07bec",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mock-pay",
        version: "sha-b7be7d73a8b0",
        digest: "d07f071fb2750e549d7509a73400ca1bcb3e3f861c23681990354602b9604d60",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mock-refund",
        version: "sha-e57f6bb42cca",
        digest: "d26ecb63db16eb71b50a2e972f5a73b013ff7fd8e9e08842d29056f76f5b0584",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/moltbook",
        version: "sha-a82265e83aee",
        digest: "1295db650b43311cefa2dfe470afa6b2fa00911f474175d68d4702dd50620480",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mpp-charge",
        version: "sha-f0a25651f9ff",
        digest: "2fde12e2a17a9293bcde4b7b678d32ba52e9cb4acf861f9ad04f6835ce928214",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mpp-pay",
        version: "sha-fe7b324fe2bf",
        digest: "9fb232c26b5d8c5bc94b2fdf2f0e8521b4c6d599fa6fc7e8f2f4ce36eba3d0a0",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mpp-refund",
        version: "sha-15b6da590a11",
        digest: "f799a44a9c6f6f893b111472c36e296a6d329bba5e7838db2faa2a40ce7618d4",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/n8n-handoff",
        version: "sha-e90151c3b177",
        digest: "4b80cc93f2544862791b2645cddf15b1e43f65af6cb2fa4792867fa15668d24e",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/nitrosend",
        version: "sha-cbb92ee3fa87",
        digest: "25c1d932035cefdac9341a4978ab9c259c4a2404f7ab8dd12cac1e4ee170bbe8",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/nws-weather-forecast",
        version: "sha-d02c619b85b7",
        digest: "382cdef84f660e7cfdc2dbbfd7e8382d204d1f4ee46ffa019549615f9c2f745c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/open-meteo-weather-forecast",
        version: "sha-a8ebe46e1674",
        digest: "041e0ec18fa4b646b46b72d34662eabbbfbc43ab5a3a65423b49b3e94e81d159",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/operator-inbox",
        version: "sha-9ba09f224c37",
        digest: "e3798c5543b268e3e77a11466f093637b4d4807c2e94fd2ec869a46d288a0f28",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ops-desk",
        version: "sha-4acb4bb12e95",
        digest: "1b5066da46330f06a4402b9b06d70435c3f9f8d79b0f38bf324324870eca022d",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/organic-growth",
        version: "sha-a5ec9cc2e860",
        digest: "115d06eb9a646f67f0020ef0bb80abe3a1adfe80b8872f11d161cff39b357683",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/policy-author",
        version: "sha-05f7413a8ac1",
        digest: "9c5da4bc2950eeb8b8b060a920021671272b9232d3c265f878620ffa0d1d6c6c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/prior-art",
        version: "sha-2ac82a26a994",
        digest: "bbb454fc017ecb66b6ff96913ee049c480267873948212ae30ff38e4e69fb8eb",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/purchase-approval",
        version: "sha-81a472367b94",
        digest: "98364a1309bba05e143c1026ff953be6ee44013f38800c44ef67f62f9d93767d",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/redact-pii",
        version: "sha-235811758008",
        digest: "2358e19a81b07f70bdefee629290d7d132592b8b9f6491abedd44d4bf6837810",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/reflect-digest",
        version: "sha-f42f26daaeab",
        digest: "d5157d4d018f3e13815e0d28296cfe7d0bd97d1584f54bfc91459d23a16e59fd",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/refund",
        version: "sha-c3055046eb9a",
        digest: "737df2675292ef3e61a498513683d0020e011c169652aa602af90947c2be5acc",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/release",
        version: "sha-2579ede621c3",
        digest: "2d08998848cff00926cbcb2a75879facb29d2eed02000a72c1627643b84b486c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/research",
        version: "sha-a4e34123fd6c",
        digest: "f76d65e1e45e156b1c6e05c97cb28976b22386871883920038fba89491aa79b5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/review-skill",
        version: "sha-6b6daf6be319",
        digest: "0bb55d42aad95cdf5c2d5bd765a1dd79a2adc691b8cb6eba902b673216dfc50c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/run-history",
        version: "sha-a05ccab17632",
        digest: "cf8e8732664dddce70f2f5aebf34bed987e497c0bf400ece72b9dd619867ef2f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sbom-maker",
        version: "sha-e94fac7aefd6",
        digest: "35cbf71ec5334991992c968e3b31aa5a079f813a503d19e16dd0f2eff41fe200",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/schema-guard",
        version: "sha-dcde1af949ea",
        digest: "8cf85c86e819c47d9ff7a088a8c7b0124d2b6236a1d5ededb1def8a41bd714f9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/send-as",
        version: "sha-d3cc79374d86",
        digest: "c9e832105fd33f032c69674790d9b03bb0191d30e866d132038273730ea94ead",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/settle-invoice",
        version: "sha-6433fb9cd0dd",
        digest: "c2c0d3992c7f9dfd1cdb2cd6e5d1903b42057d14fb206f4645de008eaa8c198a",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sign-receipt",
        version: "sha-37f8eebe49a8",
        digest: "512935aa95e2884f7bf8e45b1ba0a8bc071b249f5ed296a81fe767023d0cfae3",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/skill-lab",
        version: "sha-d5cfe5a8fc67",
        digest: "a71af341081a6d1c89c71fec78db4a22defde1778626dd572fc36bd5100dad04",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/slack",
        version: "sha-c1f13af0105b",
        digest: "54c62aceb637734265165f943f3fe5f713878bf2bea42098af5bfcc27ded23ae",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/slack-notify",
        version: "sha-b3cc95a9e87d",
        digest: "50fcca88e86bd713474696ded4803910328fc17727ef73937463af00b8586023",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sourcey",
        version: "sha-d7a492dbcf2d",
        digest: "0e1cba333e15a0affafbf3452ebdf41962507e896761c14509ff7b9ea68d67b8",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/spend",
        version: "sha-5068dc41cc4a",
        digest: "add056456c397733bfbb6d1775b143b0c6aa1c15a3c9e76909d61441595ddda0",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sql-analyst",
        version: "sha-14546fe513ca",
        digest: "c8807a325e10067eaae7396a325da29d47a9dd566fe265c9f27cac2553e3144c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/stripe-charge",
        version: "sha-ece6cbefdd59",
        digest: "f511e18de56dbf0360961147049e0bb34d8a527b04681ba53df99a5a4c4788fd",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/stripe-pay",
        version: "sha-0e1587aa6d18",
        digest: "efbfe5a40d0f247f6e1c8ed4ba23da7567314272ad62736eed2dde50e0ea55c5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/stripe-refund",
        version: "sha-38d2954c3765",
        digest: "4f0a281e2767b666645751fe3f551731e9517a33f0bed2c68d9b91f96a8726f5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/taste-profile",
        version: "sha-bdac1a8def9c",
        digest: "e26a157b9e92a559593175b00abea127ad256a54842089e86f85fb9b2c29d1b5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/twitter",
        version: "sha-001009947ed1",
        digest: "d97463a3e7f660c8de52e8edc543b3d51bc128fcc841b0d9e8834d2c684ae976",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/vault-unseal",
        version: "sha-4b16f532d854",
        digest: "8165f75a60026e399d2a1548e4e8fcf0147eeeeb0dee18b171b7a6b9b422b89e",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/vuln-disclosure",
        version: "sha-9c746366a31f",
        digest: "af6c7ff61d857f346c611bbffb0689f0adaaa4adbaa460b502d8266fdb41cdae",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/vuln-triage",
        version: "sha-e348d096f6ec",
        digest: "1100857cf7c0c9337e7791cbe93838789c2c7e955f50e946d0a9624cd085d327",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/weather-forecast",
        version: "sha-7d52e1c776ba",
        digest: "b1828f4187801fe5de29c48d515ede2ffd42cab8d2ace48aab98f4aeb28cd20c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/web-fetch",
        version: "sha-7af2bc5eabe3",
        digest: "f0a140311293d2349c926b8b4f6de72753c09d85c225e5f32c0c16c770b32fbb",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/work-plan",
        version: "sha-8eac5e83418f",
        digest: "0c4b3cbe546a009c917a9fb4b3fd380db7c147c816438f742b46b3ec3c7ae6eb",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/x402-pay",
        version: "sha-decbbf9220ef",
        digest: "01a310d4f74b89373823ef5bdba7a7c1570e24275f71d680627c3517e20b9bef",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/zapier-handoff",
        version: "sha-0ea51c537096",
        digest: "fa960978f3a8325428c192badf7b449213015e8f789ab6d513c5138983ae30e9",
    },
];

pub(crate) fn official_skill_entry_by_name(name: &str) -> Option<&'static OfficialSkillLockEntry> {
    let normalized = name.trim();
    OFFICIAL_SKILLS.iter().find(|entry| {
        entry.skill_id == normalized
            || entry
                .skill_id
                .rsplit_once('/')
                .is_some_and(|(_, skill_name)| skill_name == normalized)
    })
}
