import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { Ajv2020 } from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const workspaceRoot = process.cwd();
const check = process.argv.includes("--check");

const targets = [
  {
    schema: "paid-skill-listing.schema.json",
    output: "packages/contracts/src/generated/paid-skill-listing-validator.ts",
  },
] as const;

for (const target of targets) {
  const schema = JSON.parse(
    readFileSync(path.join(workspaceRoot, "schemas", target.schema), "utf8"),
  ) as Record<string, unknown>;
  const ajv = new Ajv2020({
    allErrors: false,
    strict: false,
    validateSchema: false,
    code: { esm: true, lines: true, source: true },
  });
  const generated = standaloneCode(ajv, ajv.compile(schema));
  const imports: string[] = [];
  const portable = generated.replace(
    /^const (\w+) = require\("([^"]+)"\)(\.default)?;$/gmu,
    (_line, binding: string, specifier: string, defaultAccess: string | undefined) => {
      const moduleBinding = `${binding}Module`;
      imports.push(`import * as ${moduleBinding} from ${JSON.stringify(`${specifier}.js`)};`);
      if (!defaultAccess) return `const ${binding} = ${moduleBinding};`;
      const candidate = `${binding}Candidate`;
      return [
        `const ${candidate} = ${moduleBinding}.default;`,
        `const ${binding} = typeof ${candidate} === "function" ? ${candidate} : ${candidate}.default;`,
      ].join("\n");
    },
  );
  const source = [
    "// Generated by scripts/generate-contract-validators.ts. Do not edit by hand.",
    `// Source of truth: schemas/${target.schema}.`,
    "// @ts-nocheck -- Ajv standalone output is generated JavaScript compiled as TypeScript.",
    ...imports,
    "",
    portable.trim(),
    "",
  ].join("\n");
  const outputPath = path.join(workspaceRoot, target.output);
  if (check) {
    if (readFileSync(outputPath, "utf8") !== source) {
      console.error(`${target.output} is stale. Run pnpm contracts:validators:generate.`);
      process.exitCode = 1;
    }
  } else {
    writeFileSync(outputPath, source);
  }
}
