use super::CommandSpec;

pub const ROOT_COMMAND_SPEC: CommandSpec = CommandSpec {
    name: "cli.help",
    top_level_usage: &[],
    usage: &["runx <command> [args]", "runx --help", "runx --version"],
    notes: &[],
    options: &[
        "-h, --help",
        "-V, --version",
        "-j, --json  Emit the native command catalog with --help",
    ],
};

pub const COMMAND_SPECS: &[CommandSpec] = &[
    CommandSpec {
        name: "new",
        top_level_usage: &[],
        usage: &[
            "runx new <name> --objective text [--project-context text] [--directory dir] [-R dir] [--managed-agent [--managed-agent-rounds n]] [--non-interactive] [-j|--json]",
        ],
        notes: &[
            "Delegates to the canonical Skill Lab build lane; no files are written until the digest-bound package validates.",
            "Without --managed-agent, returns a needs_agent envelope and an exact runx resume command.",
        ],
        options: &[
            "--objective text  Required capability and outcome",
            "--project-context text  Product, repository, and operator constraints",
            "--directory dir  Child path inside the active workspace",
            "-R, --receipt-dir dir",
            "--managed-agent  Explicitly allow an in-process model loop for this run",
            "--managed-agent-rounds n  Bound each managed act to 1-32 rounds (default 4)",
            "--non-interactive",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "init",
        top_level_usage: &[],
        usage: &["runx init [-g|--global] [--prefetch official] [--json]"],
        notes: &[],
        options: &[
            "-g, --global",
            "--prefetch official  Prefetch the official skill catalog",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "verify",
        top_level_usage: &[],
        usage: &[
            "runx verify [receipt-id] [--receipt-dir dir] [--receipt <path|->] [--notary <path|-> --notary-key trusted.pem] [-j|--json]",
        ],
        notes: &[],
        options: &[
            "--receipt-dir dir",
            "--receipt <path|->",
            "--notary <path|->",
            "--notary-key trusted.pem",
            "--allow-local-development-signatures  Accept local fixture signatures only; never for production verification",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "history",
        top_level_usage: &[],
        usage: &[
            "runx history [query] [--detail] [--skill s] [--status s] [--source s] [--actor a] [--artifact-type t] [--since iso] [--until iso] [--limit n] [--receipt-dir dir] [--json]",
        ],
        notes: &[],
        options: &[
            "--skill s",
            "--status s",
            "--source s",
            "--actor a",
            "--artifact-type t",
            "--since iso",
            "--until iso",
            "--limit n",
            "--receipt-dir dir",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "resume",
        top_level_usage: &[],
        usage: &[
            "runx resume <run-id> <answers.json> [-R dir] [--package-digest sha256] [--execution-closure-digest sha256] [--managed-agent [--managed-agent-rounds n]] [--non-interactive] [-j|--json]",
        ],
        notes: &[
            "Put agent/task responses under {\"answers\": {...}}.",
            "Put explicit human decisions under {\"approvals\": {\"<request-id>\": {\"approved\": true, \"reason\": \"...\"}}}; this is a host attestation that a human approved the exact pending gate. Agents must never author it.",
        ],
        options: &[
            "-R, --receipts dir",
            "--receipt-dir dir",
            "--non-interactive  Accepted for automation; resume never prompts",
            "--managed-agent  Explicitly allow an in-process model loop for this continuation",
            "--managed-agent-rounds n  Bound each managed act to 1-32 rounds (default 4)",
            "--package-digest sha256   Reassert the checkpointed package binding",
            "--execution-closure-digest sha256",
            "                          Reassert the checkpointed execution closure",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "list",
        top_level_usage: &[],
        usage: &[
            "runx list [tools|skills|graphs|packets|overlays] [--ok-only|--invalid-only] [-j|--json]",
        ],
        notes: &[],
        options: &["--ok-only", "--invalid-only", "-j, --json"],
    },
    CommandSpec {
        name: "login",
        top_level_usage: &[],
        usage: &[
            "runx login [--provider github|google|gitlab] [--for default|publish] [--from-gh] [--api-base-url url] [--allow-local-api] [-j|--json]",
        ],
        notes: &[],
        options: &[
            "--provider provider",
            "--for purpose",
            "--from-gh            Use the active GitHub CLI identity instead of browser OAuth",
            "--api-base-url url",
            "--allow-local-api",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "connect",
        top_level_usage: &["runx connect list|start|status|revoke ... [-j|--json]"],
        usage: &[
            "runx connect list [-j|--json]",
            "runx connect start <provider> --scope <capability> [--scope <capability>...] [--scope-family family] [--authority-kind kind] [--target-repo repo] [--target-locator locator] [--binding id] [-j|--json]",
            "runx connect status <session-id> [-j|--json]",
            "runx connect revoke <grant-id> [-j|--json]",
        ],
        notes: &[],
        options: &[
            "--api-base-url url",
            "--token token",
            "--allow-local-api",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "config",
        top_level_usage: &[
            "runx config set|get|list [provider|model|api-key|public-token] [value] [-j|--json]",
        ],
        usage: &[
            "runx config set <key> <value> [-j|--json]",
            "runx config set api-key|public-token --from-stdin [-j|--json]",
            "runx config get <key> [-j|--json]",
            "runx config list [-j|--json]",
        ],
        notes: &[
            "Short keys: provider, model, api-key, and public-token. Fully qualified config keys are also accepted. Secret values are accepted only on stdin.",
        ],
        options: &["--from-stdin", "-j, --json"],
    },
    CommandSpec {
        name: "credential",
        top_level_usage: &["runx credential set|list|remove|bind ... [-j|--json]"],
        usage: &[
            "runx credential set <provider> [--profile name] [--auth-mode mode] [--audience https://host] --from-stdin [-j|--json]",
            "runx credential list [-j|--json]",
            "runx credential remove <profile> [-j|--json]",
            "runx credential bind <profile> --provider <provider> [-j|--json]",
            "runx credential bind <profile> --skill <skill> --credential <name> [-j|--json]",
        ],
        notes: &[
            "Secret material is accepted only on stdin. Profiles are stored locally with encrypted-at-rest private files; project bindings contain names only.",
        ],
        options: &[
            "--from-stdin",
            "--profile name",
            "--auth-mode mode",
            "--audience https://host",
            "--provider provider",
            "--skill skill",
            "--credential name",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "data",
        top_level_usage: &[
            "runx data migrate --database path --source ref [--backup path] [-j|--json]",
        ],
        usage: &["runx data migrate --database path --source ref [--backup path] [-j|--json]"],
        notes: &[
            "Migrates only recognized legacy SQLite event stores under the active workspace, after an exclusive consistent backup and before independent readback verification.",
            "Current stores return an idempotent proof. Unknown or partial schemas are not modified.",
        ],
        options: &[
            "--database path  Workspace-relative SQLite event-store path",
            "--source ref     Data-source reference assigned to formerly unscoped rows",
            "--backup path    Optional workspace-relative backup target",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "policy",
        top_level_usage: &["runx policy inspect|lint <policy.json> [--json]"],
        usage: &[
            "runx policy inspect <policy.json> [--json]",
            "runx policy lint <policy.json> [--json]",
        ],
        notes: &[],
        options: &["-j, --json"],
    },
    CommandSpec {
        name: "publish",
        top_level_usage: &[],
        usage: &[
            "runx publish <receipt.json> [--api-base-url url] [--token token] [--allow-local-api] [-j|--json]",
        ],
        notes: &[],
        options: &[
            "--api-base-url url  Public API base URL (default: RUNX_PUBLIC_API_BASE_URL or https://api.runx.ai)",
            "--token token       Public API token (default: RUNX_PUBLIC_API_TOKEN or runx login)",
            "--allow-local-api   Allow loopback/private public API URLs for local dogfood only",
            "-j, --json          Print the raw notary response as JSON",
        ],
    },
    CommandSpec {
        name: "kernel",
        top_level_usage: &[],
        usage: &["runx kernel eval --input <file|-> --json"],
        notes: &["Reads a deterministic kernel request from a file or stdin."],
        options: &["--input <file|->", "--json  Required"],
    },
    CommandSpec {
        name: "payment",
        top_level_usage: &[],
        usage: &["runx payment admission issue --input <file|-> --json"],
        notes: &["Issues a signed payment admission from a JSON request."],
        options: &["--input <file|->", "--json  Required"],
    },
    CommandSpec {
        name: "parser",
        top_level_usage: &[],
        usage: &["runx parser eval --input <file|-> --json"],
        notes: &["Reads a parser evaluation request from a file or stdin."],
        options: &["--input <file|->", "--json  Required"],
    },
    CommandSpec {
        name: "doctor",
        top_level_usage: &[],
        usage: &["runx doctor [path|authority|registry] [--json]"],
        notes: &[],
        options: &["-j, --json"],
    },
    CommandSpec {
        name: "dev",
        top_level_usage: &[],
        usage: &["runx dev [root] [--lane lane] [--json]"],
        notes: &[],
        options: &["--lane lane", "-j, --json"],
    },
    CommandSpec {
        name: "export",
        top_level_usage: &[],
        usage: &["runx export <claude|codex> [skill-ref...] [--project] [--json]"],
        notes: &[
            "A full export syncs the current skill workspace and prunes only shims it owns; named skill refs update additively.",
        ],
        options: &[
            "--project  Write project-local host-agent shims",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "mcp",
        top_level_usage: &[],
        usage: &[
            "runx mcp serve <skill-ref...> [--receipt-dir dir] [--http-listen [addr]] [--http-allow-non-loopback]",
        ],
        notes: &[],
        options: &[
            "--receipt-dir dir",
            "--http-listen [addr]",
            "--http-allow-non-loopback",
            "--runner runner  Must follow the serve subcommand",
        ],
    },
    CommandSpec {
        name: "skill",
        top_level_usage: &[],
        usage: &[
            "runx skill <skill-ref|owner/name@version|skill-dir|SKILL.md> [runner] [-p profile] [-i key=value] [--input-json key=json] [--inputs file|-] [-j] [--managed-agent [--managed-agent-rounds n]] [--full-operator-context] [--registry url|path] [--digest sha256] [--package-digest sha256 --execution-closure-digest sha256] [--flag value] [-R dir]",
            "runx skill inspect <skill-ref|owner/name@version|skill-dir|SKILL.md> [runner] [-j] [--registry url|path] [--digest sha256]",
        ],
        notes: &[],
        options: &[
            "-p, --profile name       Use a stored local credential profile",
            "--credential-profile name  Alias for --profile",
            "-i, --input key=value    Set a structured input; repeat for multiple inputs",
            "--input-json key=json    Set an input that must parse as JSON",
            "--inputs file|-          Read the complete JSON input object from a file or stdin; do not mix with per-key inputs",
            "--full-operator-context  Print the complete prepared context before execution",
            "--non-interactive        Never prompt; return approval instructions instead",
            "--managed-agent          Explicitly allow an in-process model loop for this run",
            "--managed-agent-rounds n Bound each managed act to 1-32 rounds (default 4)",
            "-R, --receipts dir       Write receipts under dir",
            "--receipt-dir dir        Alias for --receipts",
            "-j, --json               Print machine-readable output",
            "--registry url|path",
            "--digest sha256",
            "--package-digest sha256 Bind execution to the complete validated skill package; requires closure digest",
            "--execution-closure-digest sha256",
            "                          Bind execution to the complete native skill closure; requires package digest",
            "--flag value",
        ],
    },
    CommandSpec {
        name: "add",
        top_level_usage: &[],
        usage: &[
            "runx add <skill-ref|github-url> [--registry url|path] [--version version] [--ref git-ref] [--digest sha256] [--to dir] [--api-base-url url] [--json]",
        ],
        notes: &[],
        options: &[
            "--registry url|path  Registry URL or local registry path for skill refs",
            "--version version    Registry version for skill refs",
            "--ref git-ref        Git ref for GitHub repository URLs",
            "--digest sha256      Expected package digest for skill refs",
            "--to dir             Install destination for skill refs",
            "--api-base-url url   Hosted index API for GitHub repository URLs",
            "-j, --json",
        ],
    },
    CommandSpec {
        name: "harness",
        top_level_usage: &[],
        usage: &["runx harness <fixture.yaml...|skill-dir|SKILL.md> [-R dir] [-j|--json]"],
        notes: &["Package mode runs both inline harness.cases and sorted fixtures/*.yaml."],
        options: &["-R, --receipt-dir dir", "-j, --json"],
    },
    CommandSpec {
        name: "tool",
        top_level_usage: &[],
        usage: &[
            "runx tool build <tool-dir>|--all [--json]",
            "runx tool search <query> [--source source] [--json]",
            "runx tool inspect <ref> [--source source] [--json]",
        ],
        notes: &[],
        options: &["--all", "--source source", "-j, --json"],
    },
    CommandSpec {
        name: "registry",
        top_level_usage: &["runx registry search|read|resolve|install|package|publish ... --json"],
        usage: &[
            "runx registry search <query> [--registry url|path] [--registry-dir dir] [--limit n] [-j|--json]",
            "runx registry read <ref> [--registry url|path] [--registry-dir dir] [--version version] [-j|--json]",
            "runx registry resolve <ref> [--registry url|path] [--registry-dir dir] [--version version] [-j|--json]",
            "runx registry install <ref> [--registry url|path] [--registry-dir dir] [--version version] [--digest sha256] [--to dir] [-j|--json]",
            "runx registry package <SKILL.md|skill-dir> [--profile X.yaml] [-j|--json]",
            "runx registry publish <SKILL.md|skill-dir> [--registry url|path] [--owner owner] [--version version] [--profile X.yaml] [--trust-tier tier] [--upsert] [-j|--json]",
        ],
        notes: &[],
        options: &[
            "--registry url|path",
            "--registry-dir dir",
            "--version version",
            "--digest sha256",
            "--to dir",
            "--owner owner",
            "--profile X.yaml",
            "--trust-tier first_party|verified|community",
            "--limit n",
            "--upsert",
            "-j, --json",
        ],
    },
];
